### ISSUE TITLE
can't run examples

### ISSUE THREAD

**Issue by adv0r** [bitfloor/trader.nodejs#4]
Hi, 
I'm not able to run examples.

Maybe it depends on the node version

```
adva-mbp:examples advanced$ node market_data.js 

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Symbol microtime_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/advanced/Dropbox/playground/node bitcoin trader/node_modules/btctrader/node_modules/microtime/index.js:9:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by defunctzombie** [comment]
I haven't updated this library in quite a long time. Are you interested in the bitfloor aspects of this library or the general trading aspects. I was hoping to release a more bitfloor specific library.

**Comment by cryptal** [comment]
I'm also interested in the API library. I think adv0r's error is caused by an older version of `microtime` being required. Maybe Bump the `package.json` dep to 0.3.3 ?
