### ISSUE TITLE
Market Data example fails

### ISSUE THREAD

**Issue by cryptal** [bitfloor/trader.nodejs#5]
Running node v0.10.4 and microtime 0.3.3. Checked out the code.

```
$ npm examples/market_data.js

~/trader.nodejs/lib/books/mtgox_rest.js:45
    maybe_update(0, bid, book.bids[book.bids.length - 1]);
                                            ^
TypeError: Cannot read property 'length' of undefined
    at process_new_book (/home/dan/trader.nodejs/lib/books/mtgox_rest.js:45:49)
    at IncomingMessage.<anonymous> (/home/dan/trader.nodejs/lib/books/mtgox_rest.js:68:17)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:883:14
    at process._tickCallback (node.js:415:13)
```

**Comment by carsato** [comment]
Same error here.
I solved It by replacing mtgox.com by data.mtgox.com on "./trader.nodejs/examples/market_data.js:39" market_data.js around line 39 (i added some lines). That's the "host" property

original:
 35 var gox = books.build({
 36     exchange: 'mtgox',
 37     depth: 'L1',
 38     protocol: 'rest',
 39     host: 'mtgox.com',
 40     // specified per mtgox api v0
 41     product: 'EUR',
 42 });

replaced:
 35 var gox = books.build({
 36     exchange: 'mtgox',
 37     depth: 'L1',
 38     protocol: 'rest',
 39     host: 'data.mtgox.com',
 40     // specified per mtgox api v0
 41     product: 'EUR',
 42 });
